### ISSUE TITLE
CLI throwing syntax error

### ISSUE THREAD

**Issue by blarghmatey** [moyaproject/moya#1]
When I try to run `moya -h` from the command line I get the following stack trace:

```
Traceback (most recent call last):
  File "/data/tmacey/.virtualenvs/moyatest/bin/moya", line 9, in <module>
    load_entry_point('moya==0.5.1', 'console_scripts', 'moya')()
  File "/data/tmacey/.virtualenvs/moyatest/lib/python3.4/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/tmacey/.virtualenvs/moyatest/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/data/tmacey/.virtualenvs/moyatest/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/data/tmacey/.virtualenvs/moyatest/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/tmacey/.virtualenvs/moyatest/lib/python3.4/site-packages/moya/command/app.py", line 116
    def run(self):
SyntaxError: import * only allowed at module level
```

I am running it in a virtualenv with Python 3.4.2 and no other packages installed.

**Comment by willmcgugan** [comment]
Thanks, I'll have a fix for that in a few hours.

**Comment by willmcgugan** [comment]
Oddly I can't reproduce that. Although I do have a fix in mind.

I guess this works?

```moya help id```

**Comment by blarghmatey** [comment]
If I run `moya help id` I get the same stack trace. It seems to run into that no matter what command follows `moya`. Thanks for looking into this so quickly. This definitely seems like in an interesting project that I would like to experiment with.

**Comment by willmcgugan** [comment]
I just pushed 0.5.2 to PyPi. Can you give that a try and let me know if it works. I can't reproduce it here...

**Comment by willmcgugan** [comment]
Have you had a chance to test this? I'd like to close the ticket...

**Comment by blarghmatey** [comment]
I tested it, but I am now getting the following traceback
```
Traceback (most recent call last):
  File "/data/tmacey/.virtualenvs/moyatest/bin/moya", line 9, in <module>
    load_entry_point('moya==0.5.2', 'console_scripts', 'moya')()
  File "/data/tmacey/.virtualenvs/moyatest/lib/python3.4/site-packages/moya/command/app.py", line 308, in main
    return moya.run()
  File "/data/tmacey/.virtualenvs/moyatest/lib/python3.4/site-packages/moya/command/app.py", line 132, in run
    importlib.import_module(subcommand_module)
  File "/data/tmacey/.virtualenvs/moyatest/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/data/tmacey/.virtualenvs/moyatest/lib/python3.4/site-packages/moya/command/sub/runserver.py", line 10, in <module>
    import thread
ImportError: No module named 'thread'
```

This is using CPython 3.4.2 on 64 bit Manjaro Linux (an Arch derivative).

**Comment by willmcgugan** [comment]
Ah, thread has been renamed in Python3.

**Comment by willmcgugan** [comment]
There were a few more Python3 issues. Should be fixed now (v0.5.5)

**Comment by blarghmatey** [comment]
It is mostly working now. The only issue I'm seeing at the moment is, when running `moya runserver` I get `:moya.preflight:WARNING: No permission groups defined - run 'moya auth#cmd.init'` in the output. When trying to run the command I get ```
moya auth#cmd.init                                                                                                                                                                                                                                                        [10:04:13 AM]
zsh: no matches found: auth#cmd.init
```

**Comment by blarghmatey** [comment]
It's all working great now. Thanks!

**Comment by willmcgugan** [comment]
Excellent. Thanks for the bug report.
